export function planPrompt({ config, query, audit, observation, skill }) {
  const skillBlock = skill ? `\nINSTALLED AEO SKILL\n${skill}\n` : '';
  return `You are AEO Agent's operator: a purpose-built agent by AEOkit for improving how a real brand's public evidence can support answer-engine research.\n\nObjective: Make ${config.brand} more likely to be accurately considered and cited for this buyer question:\n${query}\n\nWork in plan-only mode. Inspect the repository and current public web sources as needed. Do not edit files. Build the smallest evidence-backed change set. Separate deterministic facts, directional simulation, and production observation. Never promise ranking or visibility gains. Every diagnosis and proposed change must cite one or more supplied evidence IDs or a full source URL. Do not invent claims, customers, statistics, dates, or comparisons.\n${skillBlock}\nBRAND PROFILE\n${JSON.stringify(config, null, 2)}\n\nDETERMINISTIC AUDIT\n${JSON.stringify({ readinessScore: audit.readinessScore, disclaimer: audit.disclaimer, findings: audit.findings, repositorySignals: audit.repository.signals, remote: audit.remote }, null, 2)}\n\nBASELINE OBSERVATION\n${observation ? JSON.stringify({ evidenceLevel: 'directional-agent-simulation', provider: observation.provider, promptHash: observation.promptHash, summary: observation.summary, observations: observation.observations?.map((item) => ({ promptId: item.promptId, analysis: item.analysis, answer: item.answer })) }, null, 2) : 'Not run. Do not infer live visibility.'}\n\nReturn Markdown with exactly these sections: Diagnosis, Hypothesis, Proposed patch, Claims that require evidence, Verification plan, and Evidence ledger. Name concrete files when the repository makes that possible.`;
}

export function applyPrompt({ config, query, proposal, toolCommand, skill }) {
  const skillBlock = skill ? `\nINSTALLED AEO SKILL\n${skill}\n` : '';
  return `You are AEO Agent's operator in explicitly approved apply mode. Implement the approved proposal in the current repository.\n\nObjective: ${query}\nBrand: ${config.brand}\nSite: ${config.site}\n\nConstraints:\n- Make a small, reviewable patch limited to public evidence, content, metadata, schema, and directly related tests.\n- Preserve existing style and unrelated user work.\n- Do not deploy, publish, commit, push, contact third parties, or change analytics accounts.\n- Do not invent facts, measurements, testimonials, dates, citations, or competitor claims. Omit a proposed claim when the repository cannot support it.\n- Keep JSON-LD consistent with visible page content.\n- Run relevant local tests or validation after editing.\n- The deterministic audit is available as: ${toolCommand} tool audit --offline --json\n- Finish with a concise summary of changed files, evidence used, tests run, and remaining production checks.\n${skillBlock}\nAPPROVED PROPOSAL\n${proposal}`;
}
